### ISSUE TITLE
SS 3.2 error: [User Error] Uncaught Exception: Object->__call(): the method 'getdisplayfoldername' does not exist on 'GridFieldBulkUpload_Request'

### ISSUE THREAD

**Issue by RVXD** [colymba/GridFieldBulkEditingTools#110]
If you click on 'From files' button error shows up in popup with release 3.2.

SS 3.2 error:
[User Error] Uncaught Exception: Object->__call(): the method 'getdisplayfoldername' does not exist on 'GridFieldBulkUpload_Request'

Trace
    Object->__call(getDisplayFolderName,Array)
    UploadField.php:1533
    GridFieldBulkUpload_Request->getDisplayFolderName()
    UploadField.php:1533
    UploadField_SelectHandler->Form()
    ViewableData.php:402
etc...

**Comment by RVXD** [comment]
Seems to work if you add this to: GridFieldBulkUpload_Request.php

	public function getdisplayfoldername(){
		$uploadField = $this->getUploadField();
		return $uploadField->getFolderName();
	}

**Comment by colymba** [comment]
Unfortunately this is a known issue. There was a similar patch to yours here:
https://github.com/colymba/GridFieldBulkEditingTools/pull/94

But to me this should be caught on `GridFieldBulkUpload.php` by the `getURLHandlers` to pass on all `UploadField` request accordingly....

**Comment by RVXD** [comment]
Thank for the quick reply, interesting. Since I didn't want to alter the code, I fixed it by temporarily adding an extension, else my client can't use 3.2:

class GridFieldBulkUpload_Request_Extension extends Extension{
	public function getdisplayfoldername(){
		$uploadField = $this->owner->getUploadField();
		return $uploadField->getFolderName();
	}
}

**Comment by colymba** [comment]
Hopefully I'll get some time soon to push some updates to this module...

**Comment by RVXD** [comment]
Ok, thanks, would be great.

**Comment by tony13tv** [comment]
Actually the solution is very simple:

Change this line:
```
return UploadField_SelectHandler::create($this, $uploadField->getFolderName());
```
with this one:
```
return UploadField_SelectHandler::create($uploadField, $uploadField->getFolderName());
```

**Comment by colymba** [comment]
thx @tony13tv! care to submit a PR? :)

**Comment by ivoba** [comment]
this was fixed in https://github.com/colymba/GridFieldBulkEditingTools/pull/94

and can you make a new release with the latest fixes, pls

**Comment by colymba** [comment]
@ivoba just tagged a new release `2.1.5`

**Comment by colymba** [comment]
this should have been fixed by https://github.com/colymba/GridFieldBulkEditingTools/pull/120 feel free to reopen if not...
