### ISSUE TITLE
Error when trying to select files via "From files"-Button

### ISSUE THREAD

**Issue by Archaeoastronom** [colymba/GridFieldBulkEditingTools#127]
Used Code:

```
$config = GridFieldConfig_RelationEditor::create();
$config->addComponent(new GridFieldBulkUpload());
$config->addComponent(new GridFieldSortableRows('SortOrder'));
$categories = new GridField("GalleryItems", "GalleryItem", $this->GalleryItems(), $config);
$fields->addFieldToTab('Root.Gallery', $categories);
```

Used Silverstripe versions: 3.2 and 3.3
When you upload files via "from your computer" it works great, but when you click on "from files" you receive an error message: "[User Error] Uncaught Exception: Object->__call(): the method 'getdisplayfoldername' does not exist on 'GridFieldBulkUpload_Request'"

**Comment by colymba** [comment]
Pretty sure this had been fixed and is actually not relevant in the latest version.
