### ISSUE TITLE
bulk unlink does not work

### ISSUE THREAD

**Issue by lekoala** [colymba/GridFieldBulkEditingTools#129]
For some reason, this line of code in handleBulkAction()

            $urlHandlers = Config::inst()->get($handlerClass, 'url_handlers',
                Config::UNINHERITED);

returns nothing. edit works fine. I'm on SilverStripe 3.3.1.

any idea?

**Comment by colymba** [comment]
Seems weird, is it with all the default settings? Do you mind posting your gridfield config code?

**Comment by lekoala** [comment]
Héhé ! Found it !

The class is named GridFieldBulkActionUnlinkHandler but the url handler is named GridFieldBulkActionUnLinkHandler (note the UnLink instead of Unlink) which prevent the config from resolving the class (at least on windows).

You need a PR or you update it yourself?

**Comment by colymba** [comment]
Nice one, yes https://github.com/colymba/GridFieldBulkEditingTools/blob/master/bulkManager/code/GridFieldBulkManager.php#L47 needs to be fixed.

If you can submit a PR all the better! 👍

**Comment by lekoala** [comment]
done, see PR https://github.com/colymba/GridFieldBulkEditingTools/pull/130

**Comment by colymba** [comment]
thanks!
