### ISSUE TITLE
Not sortable in Model admin

### ISSUE THREAD

**Issue by namnn96** [colymba/GridFieldBulkEditingTools#132]
Hi colymba,

The module works perfectly on any page types, but when I add GridFieldConfig_ManySortableRecordEditor to ModelAdmin, the records are not sortable as they lack of the sort column. Do you have any ideas on this?

Thank you

**Comment by colymba** [comment]
Hey! Which module is `GridFieldConfig_ManySortableRecordEditor` from?

**Comment by namnn96** [comment]
Ah my mistake it is from the another module. gridfieldrelationhandler
