### ISSUE TITLE
How to remove the UnLink action form bulk manager?

### ISSUE THREAD

**Issue by brasileric** [colymba/GridFieldBulkEditingTools#133]
Hi. Maybe a stupid question, but how can I remove the UnLink action from the bulk manager?

Tried:
->getComponentByType('GridFieldBulkManager')->removeBulkAction('UnLink')

But this show the error: Bulk action 'UnLink' doesn't exists.

**Comment by colymba** [comment]
That's the right method.... just need to be `unLink` with lowercase 'u':
https://github.com/colymba/GridFieldBulkEditingTools/blob/master/bulkManager/code/GridFieldBulkManager.php#L45

**Comment by brasileric** [comment]
Hi colymba,
Yes, lowercase, that's the solution....
Thanks a lot for quick response!
