### ISSUE TITLE
SilverStripe 4 compatibility

### ISSUE THREAD

**Issue by robbieaverill** [colymba/GridFieldBulkEditingTools#136]
This is a placeholder issue for tracking progress for SilverStripe 4.x compatibility.

Required as this module is a dependency of [`silverstripe/comments`](https://github.com/silverstripe/silverstripe-comments).

## Blocks

* silverstripe/silverstripe-comments#194
* silverstripe/silverstripe-blog#421

## Required

- [x] Branch current master to `2` and/or `2.1` for tracking current stable trunk separately from 4.x compat (cc @colymba)
- [x] ~Update~ Add composer alias for 3.x branch: `"extra": {"branch-alias": {"dev-master": "3.x-dev"}}`
- [x] Add namespaces and implement underlying framework namespacing including templates
- [x] Implement PSR-4 autoloader, e.g. `"autoload": {"psr-4": {"Colymba\\GridFieldBulkEditingTools\\": "code/", "Colymba\\GridFieldBulkEditingTools\\Tests\\": "tests/"}}`
- [x] Convert to PSR-2 valid style guidelines
- [x] Update required public API changes (e.g `SS_Datetime` -> `DBDatetime` and `SS_Cache` -> `Cache` etc)
- [x] Considerations for Transifex (`build.xml` is not used any more)

**Comment by robbieaverill** [comment]
I've started work on this [here](https://github.com/colymba/GridFieldBulkEditingTools/compare/master...robbieaverill:feature/ss4-compat?expand=1). I'll test it a bit before creating a PR.

**Comment by robbieaverill** [comment]
@colymba would you be able to branch off the current master for `2` or `2.1` support in future so I can pull request to your master branch?

**Comment by colymba** [comment]
@robbieaverill there is now a 2.1 branch for SS 3 compatibility.

**Comment by tractorcow** [comment]
I've now merged the comments ss 4 compat; Once this is merged we can begin working on bringing tests back to green on ss4 branches. :)

**Comment by colymba** [comment]
The basic SS4 compat is merged on the master branch so I'll close this.
