### ISSUE TITLE
[Error] Can't Upload From Files 

### ISSUE THREAD

**Issue by Bllade** [colymba/GridFieldBulkEditingTools#139]
Hi,
I'm receiving error after click on button Upload From Files

> Fatal error: Call to a member function Link() on string in /[path_to_project]/gridfield-bulk-editing-tools/bulkUpload/code/BulkUploadField.php on line 19

Uploading from computer working correctly

Button Upload From Files is working correctly when I'm trying upload single image (without gridfield-bulk-editing-tools)

SilverStripe version: 3.5.3
GridFieldBulkEditingTools vaersion: 2.1.x-dev

**Comment by colymba** [comment]
@Bllade do you still get the issue on the latest 2.1 stable? But this is probably not relevant anymore with the 3.0 work.... so maybe close this?
