### ISSUE TITLE
SilverStripe 4: setUfSetup / setUFConfig disabled

### ISSUE THREAD

**Issue by axllent** [colymba/GridFieldBulkEditingTools#141]
I realise that SS4 is work-in-progress (as is ss4-compatibility here) and that these configuration options in BulkUploader are [currently commented out](https://github.com/colymba/GridFieldBulkEditingTools/blob/master/bulkUpload/code/BulkUploader.php#L332-L347) (probably due to the upstream method changes in UploadField), but I thought it worth mentioning here to hopefully shine some light on it and help others wondering why it isn't currently working.

Keep up the great work, and nice to see you continuing to support SilverStripe 4!

**Comment by pstaender** [comment]
Hi, since ss4 is in beta and stable api, the uploader setup `ufSetup` could be reenabled (all I've tested so far is setFolderName, but it works) ?! @colymba @axllent What do you think?

**Comment by colymba** [comment]
Looking at https://github.com/silverstripe/silverstripe-framework/blob/4/src/Forms/FileHandleField.php I have a feeling `setFolderName` might be the only one working... Also not sure if any of the `config` ones are relevant anymore.

Maybe cleaning all this up and keeping only `setFolderName` is a safer approach? Or keeping `ufSetup` but testing is the method is available on the uploadField? Not sure which is best.

**Comment by pstaender** [comment]
yes, maybe `setFolderName` on `BulkUploader` feels more familiar to UploadField, so `$conf->getComponentByType('Colymba\\BulkUpload\\BulkUploader')->setFolderName('myimagefolder');` would be nice to use in my opinion.

**Comment by colymba** [comment]
am in favour too of just having a `setFolderName` method and removing the rest (ufSetup and ufConfig).

**Comment by axllent** [comment]
It appears SS4 has stripped UploadField (and related classes) back to the bare minimum. Does anyone know whether some of the older SS3 options will be re-implemented again such as `canAttachExisting` (a function I have used several times)?

I'm personally not to keen to drop all configuration options (other than `setFolderName()`) as there are at least `setAllowedFileCategories()` in FileHandleField.php which I think should be considered too.

**Comment by colymba** [comment]
@axllent I see the point. `ufConfig` can be dropped since this is not the same js and api anyway? 

So maybe we just keep `ufSetup`, but make it a bit better/simpler. I would rename the method so there is no more weird 2 letters abbreviation. It can be `setUploadFieldSetup`, `setUploadFieldConfig`, `setUploadFieldProperty`, just `uploadFieldSetup` or something else we feel is explicit and relevant.

Then when looping through all those, do a `method_exist` check or similar and throw a `User Warning` if it doesn't. What do you think?

**Comment by axllent** [comment]
@colymba That sounds good and more logical (I always had to refer to the docs as I never knew which one to use)!

In the meantime I'll search the framework issues and optionally raise a new issue regarding `canAttachExisting` as it would be good to get some clarity.

**Comment by axllent** [comment]
Just an update - I raised an "asset-admin" [issue](silverstripe/silverstripe-asset-admin#615) regarding `canAttachExisting` but they have closed the it as a "feature request" - so unless others agree they need that functionality and continue the discussion there, I'd say it's not coming back.

Another thing I only noticed today is that `->setUfSetup('setFolderName', <folder>')` doesn't seem to work any more. I'm guessing it's a beta-2 change - unfortunately I now have to deal with hundreds of images that are all located in the generic "Uploads" directory (a website in development) ;-)

**Comment by pstaender** [comment]
@axllent `->setUfSetup('setFolderName', <folder>')`  works like a charm for me in production (after uncommenting the needed part)

**Comment by axllent** [comment]
Doh, face palm... Thanks for the reminder, I forgot to uncomment that on the new installations.

**Comment by guyvanbael** [comment]
Using SS4.0 stable
I tried to set the uploadfolder as mentioned in the docs , but this uploads all the images to the uploads folder...

$config->getComponentByType('Colymba\\BulkUpload\\BulkUploader')
    ->setUfSetup('setFolderName', 'Uploads/myFolder')
    ->setUfConfig('sequentialUploads', true);

**Comment by axllent** [comment]
@guyvanbael Unfortunately that functionality is still commented out on the code. You can re-enable it simply by uncommenting out https://github.com/colymba/GridFieldBulkEditingTools/blob/master/bulkUpload/code/BulkUploader.php#L337-L340 and it should work.

It seems @colymba has other priorities at the moment.

**Comment by colymba** [comment]
@axllent yeah sorry... I did have much time lately if at all to give this repo all the love it needs.... :sad:
I always read the issues and try to help when possible and always happy to merge any PR 😄

**Comment by axllent** [comment]
@colymba I know exactly where you are coming from ;-) I would have sent a patch previously to re-enable that foldername feature (it keeps "getting me" with new installations as I have to manually modify the code - or deal with uploads all going to "Uploads"), but then there was talk about a native `BulkUploader->setFolderName()` so I wasn't sure which way to go.

My approach would be that `setFolderName()` is merely a shortcut command to the `->setUfSetup('setFolderName', 'myfolder')` method - this keeps it backwards compatible, but you may have other ideas / preferences. Either way, it would be good to get a release out (even if it is pre-release) with that fix, rather than have to use the `dev-master` and manually patch each time.

Your thoughts?

**Comment by colymba** [comment]
I'm thinking sticking with `->setUfSetup('metod', 'param')`, it makes it backward compatible and makes maintaining uploadfield method easier, the responsibility is on the dev to know which methods are available otherwise it would throw an error.

**Comment by axllent** [comment]
I agree with you @colymba. I've just submitted a pull request that re-enables the `ufSetup` (at least then I don't have to keep patching it). I started looking into the other options (eg: using `ufValidatorSetup` and un-commenting that section too) but this doesn't seem to have any affect (for instance `->setUfValidatorSetup('setAllowedExtensions', ['jpg', 'jpeg', 'png', 'gif'])` so I'm out of my depth here, sorry.  There seems to be a lot of redundant code in there so the project is in need of some serious love :) There are a lot of "features" that don't work (like attach existing file, setAllowedExtensions etc) that should either be removed from the code altogether or fixed. If you need some help then please let me know - though I may not be of much use I'm afraid.

**Comment by colymba** [comment]
@axllent thanks! PR merge. And yes, I need to spend some time an do some clean up, it's christmass soon so maybe I'll have time 🤞 

I don't think much of the other upload field config will work, since a lot of the API changed in SS4. Like `setAllowedExtensions` isn't on the `Validator` anymore, but straight on the `UplodaField` (http://api.silverstripe.org/4/SilverStripe/AssetAdmin/Forms/UploadField.html#method_setAllowedExtensions). That said, putting it into the `ufSetup` should work...

**Comment by axllent** [comment]
Thanks @colymba - at least I don't need to patch it each time for the most simple of configuration options lol :) Really appreciated!

I actually tried it in the `ufSetup` but didn't have much luck either because, despite what those docs say, it _is_ actually `$uploadfield->getValidator()->setAllowedExtensions([])` (just a heads-up before you find out the hard way). SilverStripe still need to revise those docs I suspect.

I also suspect you'll probably be looking largely at a total rewrite "based on", rather than an "upgrade of" your module (I've ended up doing that for several of my own because it was just easier). So many features have been removed in SS4 unfortunately, not to mention their jQuery -> React transition (though you can of course still use jQuery for the remainder of v4 at least). Also the transition to vendor-module would be a good step. Anyway, rather than get into all the current lacking features in this thread, I'd say you're probably well aware of them. If you need a hand at any stage I'll gladly put in some time to help you out!

**Comment by colymba** [comment]
I'll close this since https://github.com/colymba/GridFieldBulkEditingTools/pull/155 brings the functionality back... feel free to reopen if needed.
