### ISSUE TITLE
SS4-beta1: ERROR [Emergency]: Uncaught Error: Class 'SilverStripe\ORM\DataModel' not found IN POST

### ISSUE THREAD

**Issue by axllent** [colymba/GridFieldBulkEditingTools#145]
As the title says, bulkUploader returns a `ERROR [Emergency]: Uncaught Error: Class 'SilverStripe\ORM\DataModel' not found IN POST` with the latest SilverStripe4 beta1.

It is directly related to the API changes in SS, however with the API freeze I don't suspect there will be any other breaking changes like this.

**Comment by colymba** [comment]
Could you post the rest of the error dump? Thx

**Comment by axllent** [comment]
Sure thing ;-) Excuse the "source" - extracted from the FireFox network tab. In case it wasn't obvious, this is using the dev-master branch of your code.

```
ERROR [Emergency]: Uncaught Error: Class 'SilverStripe\ORM\DataModel' not found
IN POST /site/admin/pages/edit/EditForm/84/field/Images/bulkupload/upload
Line 471 in /wwwroot/site/gridfield-bulk-editing-tools/bulkUpload/code/BulkUploader.php

Source
======
  462:      * @param HTTPRequest $request
  463:      *
  464:      * @return mixed
  465:      */
  466:     public function handleBulkUpload($gridField, $request)
  467:     {
  468:         $controller = $gridField->getForm()->getController();
  469:         $handler = new \Colymba\BulkUpload\BulkUploaderRequest($gridField, $this, $controller);
  470: 
* 471:         return $handler->handleRequest($request, DataModel::inst());
  472:     }
  473: }
```

**Comment by colymba** [comment]
Fixed by https://github.com/colymba/GridFieldBulkEditingTools/pull/148
