### ISSUE TITLE
SS4: Browse / Add from files loses JS functionality after page save in CMS

### ISSUE THREAD

**Issue by axllent** [colymba/GridFieldBulkEditingTools#146]
SilverStripe 4.0.0-beta1 / GridFieldBulkEditingTools master branch

The bulkUploader uploadfield seems to loose its JavaScript click /drag-drop functionality after a page is saved and requires a full page refresh to get working again. There are no JavaScript errors on the console.

I can best illustrate this with a screen grab. I open the "Add from files" a few times which works as expected, publish the page and then try again. This affects both the Browse & the Add from files, as well as the drag & drop functionality.

![peek 2017-07-07 16-02](https://user-images.githubusercontent.com/1463435/27942791-00eb77d6-632e-11e7-94f6-0d81452d6e86.gif)

**Comment by colymba** [comment]
that's weird :)
does it happen too with the a normal upload field? And will have to check if this still happens in SS4 beta 2

**Comment by axllent** [comment]
Yeah it is weird. I suspect it has to do with the entwine JS functionality that attached itself to the upload links, and the way the new v4 CMS reloads the page after a save (react?).

The issue remains the same with SS4-beta2, and the default UploadField works as expected (no problem with that).

**Comment by axllent** [comment]
As I mentioned before this is still happening in beta2. I've done a bit of digging and can confirm that it seems the cloning functionality is what is breaking the functionality after a page save (`$('.bulkUploader').entwine({....});`). When I remove that [entire section](https://github.com/colymba/GridFieldBulkEditingTools/blob/master/bulkUpload/javascript/GridFieldBulkUpload.js#L10-L23) it works as expected, save after save.

My assumption is that the events applied to the elements work different on a page load vs: a "React load", and by cloning the element & events it causes it to break when the page is saved.

I don't actually see what that cloning function actually achieves ("Makes sure the component is at the top"), or rather where it would apply in the bulkUploader UploadField in SS4, but I'm sure you know the answer to that. Is it still needed?

**Comment by colymba** [comment]
This doesn't seem to be happening anymore, so good. Probably because a lot of the entwine code has now been removed...
