### ISSUE TITLE
Remove DataModel and Object to work with SS4

### ISSUE THREAD

**Issue by pstaender** [colymba/GridFieldBulkEditingTools#147]
Both classes where removed in the first beta version.

**Comment by pstaender** [comment]
See in pr #148

**Comment by axllent** [comment]
This fixes the same issue I reported in #145 almost a month ago.

Thanks, I hope it will get merged soon!

**Comment by colymba** [comment]
Fixed by https://github.com/colymba/GridFieldBulkEditingTools/pull/148 thanks @pstaender
