### ISSUE TITLE
SS4: "Add from files" does not actually add

### ISSUE THREAD

**Issue by axllent** [colymba/GridFieldBulkEditingTools#150]
I'm unsure as to how long this issue has existed however I just noticed that "Add from files" doesn't appear to actually add to a $has_many. 

BulkUpload allows you to select the file, adds it to the "queue"(?), but when you save the page it doesn't get added. Adding a new file however does work.

In this case a Page has a `$has_many => ['FeaturedImages' => FeaturedImage::class]` and the FeaturedImage class has a 
```
private static $has_one = [
    'Image' => Image::class,
    'Parent' => SiteTree::class
];
```

See demonstration below:

![peek 2017-09-08 11-37](https://user-images.githubusercontent.com/1463435/30190059-cd01e7c2-948b-11e7-82ac-8dda61f70697.gif)

**Comment by colymba** [comment]
This definitely doesn't work anymore in SS4. From a quick research, look around, it's because of the switch to React. So we need to write a custom hook or something to catch the addFile event...

It didn't look so straight forward to me on a first look, but maybe because I need to dive in to React more...  So any tips/help appreciated here.

**Comment by axllent** [comment]
I really don't have the answer, or even a suggestion for you @colymba. Maybe @tractorcow or @dhensby can she some light on how to best implement/integrate this?

**Comment by tractorcow** [comment]
Maybe capture what's getting posted back to the server on save? It should be the same for both add modes.

Let me know which version of framework / gfbet you are testing and I'll give it a go locally.

**Comment by colymba** [comment]
@tractorcow if I capture what's posted back to the server on save that would be outside of the gridfield mechanism, then if the user uses a mix of upload and attached I'll need to filter through what's already been created etc. and this would require a DataExtension on top fo the gridfield component am guessing...

I think what I'll try to do is look into capturing the `UPLOADFIELD_ADD_FILE` action or override the `uploadFieldReducer` or something similar... I just need to dive into React and Redux... :)

**Comment by colymba** [comment]
This took some learning from my part... especially Redux and the whole SS front-end layers. But the latest commit should address this issue (https://github.com/colymba/GridFieldBulkEditingTools/commit/de2d3234f4e40518c8266f194d38b340fbd9c577).

Basically switching to silverstripe webpack-config let me catch the uploadfield event and send the data to the bulkupload gridfield component. It is not very pretty, but for now it will do the job.

**Comment by axllent** [comment]
Thanks @colymba - I've tested (`master`) and it seems to work again when adding an existing file! There is an undefined (or rather incorrectly defined) variable in the `__construct()` which I've "fixed" in a pull request.

Previously you had a "finish" button which you have removed, which means that if one is using this module in combination with something like sortablegridfield you still need to save (or reload) the parent object (eg: page) anyway before the added items are visible in the gridfield. Previously one would click "finish" and then just reorder them without having to save the page.

Could the new (successfully uploaded) items either be auto-added to the gridfield, or a "finish" button re-added? I think in an ideal world, once completed successful uploads are added to the gridfield, and errors are displayed for those that aren't (ie: file too big).

Good work dude, thank you!

**Comment by colymba** [comment]
@axllent I know the whole bulk uploader UX is a bit off... not sure the finish button help so much more, it was refreshing the gridfield instead of the whole page but still you had to hit a button to get those lines in the gridfield.

Ultimately I would like to skip the whole `uploaditem` under the drop zone and have those go straight into the gridfield and show progress etc there. And if successful upload/attached just transform into a normal gridfield row.... but let's see how this go.... maybe 3.1 :)

**Comment by guyvanbael** [comment]
Still having this issue on new SS4.4.4 and the 3.0 release
Uploading new files are moved to the grid, but when you try to upload "from files", nothing is transfered to the grid. Workaround anyone?

**Comment by martinviolet88** [comment]
I'm having the same problem a @guyvanbael. Does anyone have a clue? Looks like it does work if i ctrl shift r the page in the CMS.. Weird
