### ISSUE TITLE
SS4 BulkUpload with many_many Image

### ISSUE THREAD

**Issue by christopherdarling** [colymba/GridFieldBulkEditingTools#152]
It looks as though many_many doesn't work on SS4 (unsure if it did on SS3... #3 seems to suggest it did). I've got a `ProductPage` Model which has `many_many` `Image`'s

Possibly related: #150  ?

**Comment by cansozeri** [comment]
I think there is noone interested about issues here :=) 29 days past and no response yet.

**Comment by colymba** [comment]
@cansozeri very much interested in the issue... but even more in fixes and PR....

**Comment by cansozeri** [comment]
@colymba Thanx for your interest. I can not use this tool because The files that uploaded with bulk tool can not stage as live version on file table. So I can not reacg them form my template. Is there any another way to accomplish this task??? I am using has many relation. I have tried everything but no luck ..

**Comment by christopherdarling** [comment]
SS 4.1.0

This doesn't appear to be working still with the following setup;

```php
class ProjectPage extends Page {
    private static $many_many = [
        'Photos' => Image::class,
    ];
}

class ProjectPageImageExtension extends DataExtension {
    private static $belongs_many_many = [
        'ProjectPages' => ProjectPage::class,
    ];
}
```

The issue appears to be in `BulkUploadHandler::createDataObject()` where it's trying to create a `DataObject` that the GridField manages (Image) and then attach the uploaded Image to that Image record which results in a 'Extension not allowed' error.

The issue occurs with both attaching existing and uploading new files.

**Comment by colymba** [comment]
@christopherdarling that's because this module is not to be used with `Image` directly. But on `DataObject` with an `Image` has_one. So your `Photos` relation should be to a DataObject... not an `Image`.

**Comment by christopherdarling** [comment]
Ahh right, maybe worth adding to the docs? Happy to PR if you would like me
to.

**Comment by colymba** [comment]
@christopherdarling happy to merge an update to the bulk uploader doc. Like a section on the bare minimum DataObject setup...
