### ISSUE TITLE
SS4 - images not show up

### ISSUE THREAD

**Issue by cansozeri** [colymba/GridFieldBulkEditingTools#153]
SS4 I can not get images that I have uploaded with bulkediting. Because I can not success that the images gonna adding to live database.

**Comment by colymba** [comment]
the module doesn't support Versioned objects yet... which is now everywhere in SS4... so until this is added... images need to be published manually...
PR welcome!

**Comment by cansozeri** [comment]
@colymba How can I publish them manually ? Is there any example about this ?? Thanx ..

**Comment by colymba** [comment]
@cansozeri you should look into the SS4 doc here (https://github.com/silverstripe/silverstripe-framework/blob/4.0/docs/en/02_Developer_Guides/00_Model/10_Versioning.md#dataobject-ownership) about the Versioning Ownership.

Basically if your parent DataObject `owns` the dataObject created by the bulkupload which in turn `owns` the images uploaded inside it. A SaveAndPublish on the parent DataObject will trigger all owned objects to be published too, so images too that are at the end of the chain.

**Comment by colymba** [comment]
BulkUploader now support auto publishing of versioned dataObjects via the `autoPublishDataObject` property. https://github.com/colymba/GridFieldBulkEditingTools/blob/master/src/BulkUploader/BulkUploader.php#L42
