### ISSUE TITLE
SS4: Edit pencil icon in framework is gone

### ISSUE THREAD

**Issue by robbieaverill** [colymba/GridFieldBulkEditingTools#158]
```
GET http://ss4.dev/gridfield-bulk-editing-tools/framework/admin/images/btn-icon/document--pencil.png 404 (Not Found)
```

From code:

```css
td a.tempDisabledEditLink
    {
      background: url('../../framework/admin/images/btn-icon/document--pencil.png') no-repeat 2px 0px;
```

We could use one of the core font icons instead, e.g. `font-icon-edit`

On a side note, if we're referencing assets from other modules we need to use the PHP requirements API now really

**Comment by colymba** [comment]
in all honesty, I think this comes from a quirk and dirty implementation when writing the first lines of code, to get something there. :sweat_smile:

I wouldn't want to reference other module's assets, even though they are core modules, and this is something I would see implemented at the same time as moving the handler's config on the handler itself, like discussed here: https://github.com/colymba/GridFieldBulkEditingTools/issues/109

so.... I probably need to get cracking on the handler config rewrite 😅
