### ISSUE TITLE
BUG Cannot install with 3.x-dev constraint

### ISSUE THREAD

**Issue by robbieaverill** [colymba/GridFieldBulkEditingTools#165]
See example Travis build failure: https://travis-ci.org/silverstripe/recipe-blog/jobs/346109794#L472-L477

Error reports a failure to install `3.x-dev` constraint, which is what is defined for the master branch: https://github.com/colymba/GridFieldBulkEditingTools/blob/master/composer.json#L22-L25 - this should work

Packagist doesn't show up the `3.x-dev` constraint - perhaps the webhook to packagist is out of date, or needs a manual refresh? https://packagist.org/packages/colymba/gridfield-bulk-editing-tools

**Comment by colymba** [comment]
Yeah I've been getting error report about branch 2.1 invalid license code.
Just did a quick edit from my phone, hopefully that will solve it. If not I'll look into it in the morning.

**Comment by robbieaverill** [comment]
Yep, that's got it. Thanks!
