### ISSUE TITLE
template folder name

### ISSUE THREAD

**Issue by wubies** [colymba/GridFieldBulkEditingTools#166]
BulkUploader.ss can't be found on UNIX systems due to case issue.
Need to change "templates/Colymba/Bulkupload/BulkUploader.ss" to "templates/Colymba/BulkUpload/BulkUploader.ss"
(Note, adding upper camel case to containing "BulkUpload" folder.

**Comment by colymba** [comment]
Fixed by https://github.com/colymba/GridFieldBulkEditingTools/pull/167
