### ISSUE TITLE
Fatal error: Bulk action handler not found: spam

### ISSUE THREAD

**Issue by digi-brains** [colymba/GridFieldBulkEditingTools#169]
After installing the comments module, which in turn installs this module; after a dev/build, clicking on any page in the cms results in this error.

**Comment by colymba** [comment]
The spam handler comes from the comments module.

Which versions of the modules are u using?

**Comment by digi-brains** [comment]
"silverstripe/comments" : "3.0.0"
"silverstripe/spamprotection" : "3.0.0"
"undefinedoffset/silverstripe-nocaptcha" : "2.0.0-alpha2"

Should I file this issue in the comments module?

**Comment by colymba** [comment]
Not a bad idea to file the issue there as well. Especially since this module had quite a few API changes.

**Comment by colymba** [comment]
issue was from the comment module (https://github.com/silverstripe/silverstripe-comments/issues/231) which has now been resolved there.
