### ISSUE TITLE
Undefined variable $firstAction

### ISSUE THREAD

**Issue by bumbus** [colymba/GridFieldBulkEditingTools#170]
Hi there,
here is an undefined variable in use:
https://github.com/colymba/GridFieldBulkEditingTools/blob/3.0/src/BulkManager/BulkManager.php#L276

**Comment by colymba** [comment]
branch 3.0 is out of date, please use master for SS4 compatibility for now... once we have stable 3.0 version, I'll republish the 3.0 branch
