### ISSUE TITLE
SS4: Newly added files aren't moved to the gridfield.

### ISSUE THREAD

**Issue by bummzack** [colymba/GridFieldBulkEditingTools#172]
Using SilverStripe 4.1 and the `master` branch of this module.

When I add new files, there's no way to "move" them to the GridField. Saving the page doesn't change anything. This is how this looks:

![screen shot](https://user-images.githubusercontent.com/1006185/37390482-8aef7d7a-2768-11e8-90ff-cd775f8e70e1.png)

In the 3.x branch, there was a special button to finalize an upload which seems to be missing now. The only way to move the items down to the GridField is by reloading the page.

Also, there seems to be another (possibly related) quirk. Add new files via _Browse_, then remove them. After the page is reloaded, these files show up in the GridField.

**Comment by colymba** [comment]
@bummzack I know! And there is a fix coming up (with some mention here https://github.com/colymba/GridFieldBulkEditingTools/issues/150), hang tight! :)
Basically I've been rewriting how bulk tools (manager + uploader) send their json response to the client and how these are handled to update the gridfield.

The gridfield will get updated automatically with the result of each action upload or manager (updating rows, deleting remove ones and handling errors much better now), so to have a smooth ux. For the upload, successful uploads will be moved at the top of the gridfield automatically, with only failed uploads staying at the top.

And all this is coming in the next couple days...

**Comment by bummzack** [comment]
Thanks for the quick feedback. Waiting impatiently :)

**Comment by colymba** [comment]
@bummzack just pushed an update bc2b317a35a53f94413253ec1908da342b84dad6 in the master branch which implement a unified response format and updates the gridfield automatically.

This will now set the base for future updates and should make the UX way better :)
I need to work on writing better code for Redux so to handle actions better and ultimately remove successfully uploaded item from the queue... stay tuned...

**Comment by bummzack** [comment]
Wow, that was fast. I now get an error (notice) whenever I upload a file:

> ERROR [Notice]: Undefined variable: message IN POST /admin/pages/edit/EditForm/18/field/Images/bulkupload/upload Line 114 in /shared/httpd/project/vendor/colymba/gridfield-bulk-editing-tools/src/BulkTools/HTTPBulkToolsResponse.php

**Comment by colymba** [comment]
@bummzack that one got missed, sorry. Should be fixed now.
