### ISSUE TITLE
Issue in handleBulkUpload in case the controller/requesthandler does not have method pushCurrent

### ISSUE THREAD

**Issue by bumbus** [colymba/GridFieldBulkEditingTools#174]
Hi there,
i just recognized that bulkuploading fails in case the controller is not a SilverStripe\CMS\Controllers\CMSPageEditController.

I have not seen any side effects when this line is just commented out: https://github.com/colymba/GridFieldBulkEditingTools/blob/7f2045e7aa6a28650c616445bb58dd81971839f9/src/BulkUploader/BulkUploader.php#L334

Maybe you can just guard this function call, if it is still needed:

```
$controller = $gridField->getForm()->getController();
if ($controller->hasMethod('pushCurrent')) {
     $controller->pushCurrent();
}
```

**Comment by robbieaverill** [comment]
`pushCurrent()` is defined in `SilverStripe\Control\Controller` (framework). Are you using a request handler instance of some sort that doesn't extend from Controller? I think it could be unwise to do so

**Comment by bumbus** [comment]
im using it to bulk upload children of https://github.com/dnadesign/silverstripe-elemental-list

The controller in this case is a SilverStripe\Versioned\VersionedGridFieldItemRequest

**Comment by robbieaverill** [comment]
Right, so that would probably be the same case for any versioned items in GridField

**Comment by colymba** [comment]
So do you think this should be implemented on the VersionedGridfield side then? Otherwise here we can loop through getController until we get one with pushCurrent available, but not sure how that looks...

**Comment by ggrune** [comment]
https://github.com/andrewhoule/silverstripe-photogallery is brooken to with the same error.

**Comment by Spambanjo** [comment]
I faced this issue yesterday, I eventually solved it by creating an extension for VersionedGridFieldItemRequest class. Simply adding a pushCurrent() function to the VersionedGridFieldItemRequest which returns null does the trick and allows me to use the BulkUploader on my DataObject. So far I haven't seen any negative side effects.

mysite/code/fixes/VersionedGridFieldItemRequestExtension.php
```
namespace Silverstripe\YourNamespace;

use SilverStripe\Core\Extension;
use SilverStripe\Control\Controller;

class VersionedGridFieldItemRequestExtension extends Extension {
    public function pushCurrent(){
        return null;
    }
}
```

mysite/_config/config.yml
```
SilverStripe\Versioned\VersionedGridFieldItemRequest:
  extensions:
    - Silverstripe\YourNamespace\VersionedGridFieldItemRequestExtension
```

**Comment by colymba** [comment]
OK, so it seems this would happen on any kind of nested Gridfield... so the `handleBulkUpload` needs some work to work in all cases, and this most likely affects also the `handleBulkAction`...

**Comment by mlewis-everley** [comment]
I am getting this issue as well, using the BulkUploader on a `DataObject` that I am managing via `ModelAdmin`.

The problem is this line: https://github.com/colymba/GridFieldBulkEditingTools/blob/master/src/BulkUploader/BulkUploader.php#L334

When using `ModelAdmin` the current controller is an instance of `GridFieldDetailForm_ItemRequest` (which doesn't extend controller, so doesn't have push current).

**Comment by colymba** [comment]
this happens on nested gridfield too, but it shouldn't be a big thing to fix... just haven't had the time to fix and test yet

**Comment by mlewis-everley** [comment]
Hey @colymba I am still getting this issue, have you got any ideas on a fix? I might be able to do a pull request if you have any ideas what can be done to fix the issue?

**Comment by colymba** [comment]
@mlewis-everley not 100% sure on the impact it would have with probably just deleting the `pushCurrent` would help. The thing am not sure is how it will affect the the following request handler and if it will still match the right portions of the URL to its own action... might need deeper testing on both `handleBulkAction` and `handleBulkUpload`.

Any help testing this and PR most welcome 😄

**Comment by mlewis-everley** [comment]
Right, I tried removing `Controller::pushCurrent` but that seems to break `ModelAdmin` (the GridField refreshes but nothing changes).

So instead I made the following amend and tested on a local project using `SilverCommerce` (which makes extensive use of `BulkManager`):

```php
public function handleBulkAction($gridField, $request)
    {
        $controller = $gridField->getForm()->getController();

        // If we cannot work with the current controller, get the currently active
        if (!$controller || $controller && !method_exists("pushCurrent", $controller)) {
            $controller = Controller::curr();
        }

        $actionUrlSegment = $request->shift();
        $handlerClass = $this->config['actions'][$actionUrlSegment];

        $controller->pushCurrent();
        $handler = Injector::inst()->create($handlerClass, $gridField, $this);
        if ($handler)
        {
            return $handler->handleRequest($request);
        }

        user_error('Unable to find matching bulk action handler for ' . $actionUrlSegment . ' URL segment.', E_USER_ERROR);
    }
```

It may be overkill, but it works with both top level gridfields (like in `ModelAdmin`), on nested GridFields and GridFields on Pages.

@colymba What are your thoughts?

**Comment by mlewis-everley** [comment]
Right, just tried adding:

```
$controller = $gridField->getForm()->getController();

var_dump($controller);
var_dump(Controller::curr());
```

And got the follow:

```
/home/morven/Projects/ss-4/vendor/colymba/gridfield-bulk-editing-tools/src/BulkManager/BulkManager.php:350:
object(SilverCommerce\CatalogueAdmin\Admin\CatalogueAdmin)[503]

/home/morven/Projects/ss-4/vendor/colymba/gridfield-bulk-editing-tools/src/BulkManager/BulkManager.php:351:
object(SilverCommerce\CatalogueAdmin\Admin\CatalogueAdmin)[503]
```

Looks like both return the same, so you may be right @colymba ?

**Comment by colymba** [comment]
thx @mlewis-everley yeah seems right, so `Controller::curr()` would be a bullet proof option and simplify the whole thing.

**Comment by mlewis-everley** [comment]
OK, did you want to implement this? Or did you want a pull request?

**Comment by colymba** [comment]
@mlewis-everley a PR would be most welcome, thanks! Otherwise I'll find some time next week...

**Comment by mlewis-everley** [comment]
Submitted PR, as I have said though, I don't use `BulkUploader`, but have added the fix to that too. Might be helpful to see if if fixes the issues @bumbus and @Spambanjo were getting?

**Comment by colymba** [comment]
I'l mark this as solved by https://github.com/colymba/GridFieldBulkEditingTools/pull/184 unless someone wants to revived this...
