### ISSUE TITLE
SS4.1: JS AJAX doesn't work correctely

### ISSUE THREAD

**Issue by a2nt** [colymba/GridFieldBulkEditingTools#176]
Plz, take a look at the issue here: https://github.com/symbiote/silverstripe-gridfieldextensions/issues/257

I have fixed it this way:
```
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'colymba/gridfield-bulk-editing-tools:client/dist/js/main.js'
    - 'colymba/gridfield-bulk-editing-tools:client/lang/en.js'
  extra_requirements_css:
    - 'colymba/gridfield-bulk-editing-tools:client/dist/styles/main.css'
```

So guess the problem is at bulk editing tools

**Comment by purplespider** [comment]
I too have hit this issue.

To reproduce:

**1. Create new SilverStripe 4 Project:**
`composer create-project silverstripe/installer /path/to/project 4.1.1`

**2. Install this module:**
`composer require colymba/gridfield-bulk-editing-tools 3.*`

**3. Update Page.php to include a GridField with a BulkUploader:**:
````
<?php

use SilverStripe\CMS\Model\SiteTree;
use SilverStripe\Forms\GridField\GridFieldConfig_RecordEditor;
use SilverStripe\Forms\GridField\GridField;
use SilverStripe\Security\Member;
use Colymba\BulkUpload\BulkUploader;

class Page extends SiteTree
{
    private static $db = [];

    private static $has_one = [];
    
    function getCMSFields() {
        $fields = parent::getCMSFields();
        
        $config = GridFieldConfig_RecordEditor::create();
        $config->addComponent(new BulkUploader());
        $gridField = new GridField("Members", "Members", Member::get(), $config);
        $fields->addFieldToTab("Root.Members", $gridField);
        
        return $fields;
    }
}
````

**4. Do a dev/build**

**5. Go to /admin**

**6. Click on any page**

**7. Change the Page Name**

**8. Click Publish**

**What happens?**
The page title in the Site Tree should update and the "Save" and "Publish" buttons should change to "Saved" and "Published" but they do not.

**Important:** The bug only seems to occur if you first go to /admin/pages then click a page. If you refresh the CMS while editing a page, the issue will not occur.

**Comment by purplespider** [comment]
Could be something to do with the contents of `colymba/gridfield-bulk-editing-tools:client/dist/js/main.js` that breaks when included over AJAX.

As if I replace the contents of `main.js` with something such as `document.body.style.color = "green";`, then it loads fine and doesn't break the CMS AJAX as above.

**Comment by colymba** [comment]
Do you guys see any JS error in the console? Or anything at all?

**Comment by robbieaverill** [comment]
I think this is the same problem we're seeing in CWP 2.x projects, where you see a "parsererror" message show up. I've traced this to having been introduced between https://github.com/colymba/GridFieldBulkEditingTools/compare/3.0.0-beta2...3.0.0-beta3.

For more information: https://github.com/silverstripe/cwp/issues/141.

If the fix/workaround is to include the assets globally in the CMS rather than only when the components are used, we could probably implement that in the meantime, but in my opinion the way that it's implemented at the moment is fine and should work, so there could be a core bug here too.

**Comment by lekoala** [comment]
I just got the same issue. I think it would save time for a lot of people to include the current requirements globally until this issue is fixed, because it basically breaks ajax on the whole cms.

**Comment by a2nt** [comment]
@lekoala I have fixed the issue some time ago by removing jquery requirement in a module and made commit into their repo. the CMS required some file like vendor.js where was jquery already included, another module required jquery again and rewrote global jquery variables. Try to check it and guess u will find solution

**Comment by robbieaverill** [comment]
Yes we have seen some weird issues with jQuery being required from modules. I suspect that in SS3 the requirement call was the same as the cms so it would’ve been ignited. Now we either bundle it in or use a different version so it may be including it twice

**Comment by robbieaverill** [comment]
I think we can always assume the cms has jQuery available

**Comment by colymba** [comment]
@robbieaverill the main change I think between https://github.com/colymba/GridFieldBulkEditingTools/compare/3.0.0-beta2...3.0.0-beta3 is the introduction to the new JS code with React and Redux... it was a full rewrite so I might have missed something? Might need to check in the React and Redux console if anything useful shows up there...

**Comment by robbieaverill** [comment]
@colymba yeah, thanks - I've been meaning to have another look but haven't gotten around to it yet.

**Comment by colymba** [comment]
@robbieaverill sorry I've been a bit out of the loop lately... I'll get my environment back up and running and try to get things moving on my side...

**Comment by guyvanbael** [comment]
any news on this one? i have several SS4 projects where i have this issue

**Comment by christopherdarling** [comment]
Same here, I'm finding that this is breaking the rest of my x-include-js headers from loading. jQuery is firing an error callback due to parsererror when loading `/resources/vendor/colymba/gridfield-bulk-editing-tools/client/dist/js/main.js`

**Comment by guyvanbael** [comment]
any news on this one?
