### ISSUE TITLE
Class 'RequestHandler' not found in

### ISSUE THREAD

**Issue by CodeLearner21** [colymba/GridFieldBulkEditingTools#182]
Hello,
I have already used this addon with SilverStripe 3, but when I tried to install again with SilverStripe 4 using composer I got "Fatal error: Class 'RequestHandler' not found in" and also module installed in /root folder instead of /root/vendor

Can you please help me with the correct steps for installation?

Thanks.

**Comment by robbieaverill** [comment]
@CodeLearner21 which version are you using please

**Comment by CodeLearner21** [comment]
After installation composer.json showing "colymba/gridfield-bulk-editing-tools": "^2.1"

I just used "composer require colymba/gridfield-bulk-editing-tools" as mention in Readme

**Comment by robbieaverill** [comment]
I see. the 2.1.x release line is for SilverStripe 3, but it uses a dangerous constraint which lets Composer think it can be used on SilverStripe 4: https://github.com/colymba/GridFieldBulkEditingTools/blob/v2.1.10/composer.json#L20

The release line you want to use is 3.0. It's not stable yet, but you can use it with `composer require colymba/gridfield-bulk-editing-tools ^3.0@dev`

**Comment by CodeLearner21** [comment]
Thanks for your help @robbieaverill, it is working now

**Comment by robbieaverill** [comment]
Here's an identical issue for your reference: https://github.com/colymba/GridFieldBulkEditingTools/issues/151
