### ISSUE TITLE
addSuccessRecords() and addFailedRecords() return invalid JSON

### ISSUE THREAD

**Issue by mlewis-everley** [colymba/GridFieldBulkEditingTools#187]
When adding a DataList to either of these functions results in multiple JSON strings being returned in the same response. This is invalid JSON so the bulk handler falls over! 

One of the functions is: https://github.com/colymba/GridFieldBulkEditingTools/blob/master/src/BulkTools/HTTPBulkToolsResponse.php#L200

Very simple example code (heavily abbreviated):

```php
class MyHandler extends Handler
{
    public function doathing()
    {
        $response = new HTTPBulkToolsResponse(false, $this->gridField);

        $response->addSuccessRecords($this->getList());
        $response->setMessage("This will result in a 500 error");
        return $response;
    }
}
```

## PRs
- https://github.com/colymba/GridFieldBulkEditingTools/pull/271

**Comment by pschiffe** [comment]
I also see this issue after upgrading from SS 3 to 5. This change fixed it for me, I'm just not sure if it's 100% safe for every use case:
```diff
diff --git a/public_html/vendor/colymba/gridfield-bulk-editing-tools/src/BulkTools/HTTPBulkToolsResponse.php b/public_html/vendor/colymba/gridfield-bulk-editing-tools/src/BulkTools/HTTPBulkToolsResponse.php
index 6c6c930..a690878 100644
--- a/public_html/vendor/colymba/gridfield-bulk-editing-tools/src/BulkTools/HTTPBulkToolsResponse.php
+++ b/public_html/vendor/colymba/gridfield-bulk-editing-tools/src/BulkTools/HTTPBulkToolsResponse.php
@@ -196,7 +196,7 @@ class HTTPBulkToolsResponse extends HTTPResponse
      */
     public function addSuccessRecords(SS_List $records)
     {
-        array_push($this->successRecords, $records->toArray());
+        $this->successRecords = array_merge($this->successRecords, $records->toArray());
         return $this;
     }

```

**Comment by GuySartorelli** [comment]
The issue description mentions `addFailedRecords` but I'm guessing someone fixed that at some stage, since it doesn't exhibit this problem.

PR merged for `addSuccessRecords`. It will be automatically tagged by GitHub actions.
