### ISSUE TITLE
PAjax request for CMS page throws "Cannot mutate DI container"

### ISSUE THREAD

**Issue by maxime-rainville** [colymba/GridFieldBulkEditingTools#188]
# Affected version
* colymba/gridfield-bulk-editing-tools 3.0.0-beta4
* Silverstripe 4.3

# Description
If you are viewing a page in the CMS and then navigate to a page containing a gridfield, you will get a nasty JS errors. 

```
Error: "Cannot mutate DI container after it has been initialised"
```

The error stack doesn't explicitly point to anything in `colymba/gridfield-bulk-editing-tools`. However, the error goes away if your remove the module.

If you refresh that page you do not get any error, even on navigation.

This got notice while working on https://github.com/silverstripe/silverstripe-cms/issues/2230. It use to block other request, but it got fix by https://github.com/silverstripe/silverstripe-admin/pull/769.

# Steps to reproduce
* Start on the `admin/pages` url.
* Navigate to a page with a Gridfield.

Notice the error in the console.

https://youtu.be/qJMFiwKbEOU

**Comment by robbieaverill** [comment]
Also related: https://github.com/colymba/GridFieldBulkEditingTools/issues/176

I think we need to set aside some time to fix these bugs soon!
