### ISSUE TITLE
Uncaught syntax error when uploading more than 2 images

### ISSUE THREAD

**Issue by dawb** [colymba/GridFieldBulkEditingTools#214]
Currently receiving the following error when uploading more than 2 images. The first 2 items upload correctly and then anything following returns this. I am currently using the latest master branch on SS 4.7.3

Has anyone else experienced the below or knows how to resolve?

`bundle.js?m=1622491141:1 Uncaught SyntaxError: Unexpected token { in JSON at position 3523
    at JSON.parse (<anonymous>)
    at t.value (bundle.js?m=1622491141:1)
    at t.value (bundle.js?m=1622491141:1)
    at t.value (bundle.js?m=1622491141:1)
    at t.value (bundle.js?m=1622491141:1)
    at t.value (bundle.js?m=1622491141:1)
    at XMLHttpRequest.r.onload (bundle.js?m=1622491141:1)`

**Comment by emteknetnz** [comment]
Looks like it's related to this https://github.com/silverstripe/silverstripe-framework/issues/9955

**Comment by emteknetnz** [comment]
Hi @dawb - looks like this was related to some over-eager error-reporting

We've released [3.0.1](https://github.com/colymba/GridFieldBulkEditingTools/releases/tag/3.0.1) which should fix this issue for you

Let us know if you have any further issues

**Comment by dawb** [comment]
Thanks @emteknetnz , this has resolved the issue for us.
