### ISSUE TITLE
[SS5] Upload fails due to non-existing Convert::json2array call

### ISSUE THREAD

**Issue by Zazama** [colymba/GridFieldBulkEditingTools#234]
Hi,

the following line calls the method Convert::json2array which has been removed from Silverstripe 5: https://github.com/colymba/GridFieldBulkEditingTools/blob/4.0/src/BulkUploader/BulkUploadHandler.php#LL117C38-L117C38

The changelog suggests using json_decode instead (https://docs.silverstripe.org/en/5/changelogs/5.0.0/), would you be able to take a look at this or accept a PR?
I changed the line to `$responseData = json_decode($uploadResponse->getBody(), true);` and it works again.

**Comment by GuySartorelli** [comment]
Fixed in [4.0.1](https://github.com/colymba/GridFieldBulkEditingTools/releases/tag/4.0.1)
