### ISSUE TITLE
deprecated method SilverStripe\Core\Convert::raw2json() - use json_encode() instead

### ISSUE THREAD

**Issue by jalamanderman** [colymba/GridFieldBulkEditingTools#261]
Hello,

Just pointing out this method should be updated for Silverstripe 5 compatibility. 

https://github.com/colymba/GridFieldBulkEditingTools/blob/f2e46f3a06c467187dce0047a2ea7afe4962ff1a/src/BulkManager/BulkAction/EditHandler.php#L377

https://docs.silverstripe.org/en/5/changelogs/5.0.0/#silverstripe-framework

"Removed deprecated method SilverStripe\Core\Convert::raw2json() - use json_encode() instead"

**Comment by GuySartorelli** [comment]
Closed as fixed in [4.0.2](https://github.com/colymba/GridFieldBulkEditingTools/releases/tag/4.0.2) (thanks for reminding me to release that)
