### ISSUE TITLE
Column name `Select` is not translatable

### ISSUE THREAD

**Issue by pschiffe** [colymba/GridFieldBulkEditingTools#268]
### Module version(s) affected

4.0.2

### Description

Hello, it's not possible to translate column name with select boxes, here:
https://github.com/colymba/GridFieldBulkEditingTools/blob/88a08f5387deeefa7154ab56d3e1afab0977fc4d/src/BulkManager/BulkManager.php#L251

![Screenshot 2024-02-24 at 20-07-06 Jedáleň - Menu](https://github.com/colymba/GridFieldBulkEditingTools/assets/3899107/0f81b4d7-b7f6-4f93-b9ec-c851f0a86ef0)

### How to reproduce

Check source.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment]
Thanks for pointing this out. Would you like to raise a pull request to resolve this? If so please target the `3.1` branch so this can be resolved for both CMS 4 and 5.

**Comment by GuySartorelli** [comment]
Thanks for resolving that.
As mentioned in the PR, it will be automatically tagged by GitHub Actions.
