### ISSUE TITLE
Inconsistent CMS widths

### ISSUE THREAD

**Issue by kinglozzer** [colymba/GridFieldBulkEditingTools#294]
### Module version(s) affected

3.1.1+

### Description

CMS widths are a bit busted when bulk editing - the LH menu width varies based on browser width:

<img width="1345" alt="Screenshot 2024-07-08 at 11 33 50" src="https://github.com/colymba/GridFieldBulkEditingTools/assets/1655548/704aac8f-fac3-4675-a507-a4d99053284f">

### How to reproduce

No specific steps other than enabling `BulkManager`, then bulk editing records. Seems to be more noticeable at smaller screen sizes.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/colymba/GridFieldBulkEditingTools/pull/295

**Comment by GuySartorelli** [comment]
Fixed in https://github.com/colymba/GridFieldBulkEditingTools/pull/308
Will be automatically tagged by GitHub Actions (I hope - not sure we've ever tested that on this repo - I'll keep an eye on it)
