### ISSUE TITLE
Enhance the "onBulkUpload" extension point so new DataObjects can be altered

### ISSUE THREAD

**Issue by mooror** [colymba/GridFieldBulkEditingTools#296]
### Description

I propose that the `$fileID` and `$record` variables be made available to the "onBulkUpload" extension point that is in the `createDataObject()` method (in `BulkUploadHandler.php`). This would allow developers to easily set additional fields on the newly created records and use data from the uploaded file to do so.

### Additional context or points of discussion

**Example usage:**
I have a DataObject with a Title, Type, and Image relationship field. Once the Bulk uploader creates new DataObjects for the images, I want to use the title of the image (which I should be able to access aftering getting the image record with the ID of `$fileID`) to generate a Title for the DataObject. I also wish to set the Type field while I am at it. 

This change would allow me to do that using the "onBulkUpload" extension point.

### Validations

- [X] You intend to implement the feature yourself
- [X] You have read the [contributing guide](https://docs.silverstripe.org/en/contributing/code/)
- [X] You strongly believe this feature should be in core, rather than being its own community module
- [X] You have checked for existing issues or pull requests related to this feature (and didn't find any)

## PRs
- https://github.com/colymba/GridFieldBulkEditingTools/pull/303

**Comment by mooror** [comment]
Closed the old PR and created a new one

**Comment by GuySartorelli** [comment]
PR merged. This will be included in the October minor release.

**Comment by mooror** [comment]
Horray! :confetti_ball:.

Thank you @GuySartorelli
