### ISSUE TITLE
Images should be added in alphabetical order

### ISSUE THREAD

**Issue by purplespider** [colymba/GridFieldBulkEditingTools#82]
When batch uploading several images, they seem to display in alphabetical order while they are uploading, but upon clicking "Finish" they end up being saved in a random order.

Ideally the precise order would be a config option, but alphabetical by name seems good default, and certainly better than the current (random?) order.

Thanks.

**Comment by bueckl** [comment]
@purplespider I ran into the same problem. Can u tell me please, what you did to fix the sort order problem?

Cheers
