### ISSUE TITLE
Bulk Manager javascript

### ISSUE THREAD

**Issue by a2nt** [colymba/GridFieldBulkEditingTools#95]
I'm working on GridField blocks module, but bulk manager won't be compatible with it cuz of excess jQuery selectors. For an instance $('td.col-bulkSelect') should be replaced with $('.col-bulkSelect') 
![screen shot 2014-11-21 at 3 10 49 pm](https://cloud.githubusercontent.com/assets/672794/5140099/dc7cb75a-7188-11e4-8092-0919ada4cf8c.png)

**Comment by colymba** [comment]
Closing this since not directly related to this component and I am not willing (at least for now) to change the selector since I think the gridfield should still be built around table for broader compatibility.
