### ISSUE TITLE
performing bulkaction delete leaves images in files

### ISSUE THREAD

**Issue by guyvanbael** [colymba/GridFieldBulkEditingTools#97]
After apllying the bulkdelete action. All images still reside in the files section of the cms.
I guess normal behaviour should be that images are deleted there. Unlink-action should leave them there.

**Comment by colymba** [comment]
This is somewhat expected behaviour actually since the component actually acts on DataObjects.

I've usually just a few line in the DataObject's onBeforeDelete hook to get rid of the image at the same time. And this gives developers more flexibility.

**Comment by guyvanbael** [comment]
what is the difference with the bulk unlinking action then?

**Comment by colymba** [comment]
"delete" delete the dataobject completely. Unlink just removes it from the relation so it can be reused.

**Comment by guyvanbael** [comment]
can you send me the onBeforeDelete code pls?

**Comment by colymba** [comment]
```php
public function onBeforeDelete()
{
  parent::onBeforeDelete();

  $image = $this->Image();
  if ( $image && $image->ID )
  {
    $image->delete();
  }
}
```
to be added to your dataobject that contains the image has_one relation (here named `Image`)
